### ISSUE TITLE
Missing get all tickers

### ISSUE THREAD

**Issue by nielskool** [sammchardy/python-kucoin#45]
The function get_ticker has the optional variable symbol but doenst work when symbol is not set.

```
def get_ticker(self, symbol):
data = {
            'symbol': symbol
        }
        return self._get('market/orderbook/level1', False, data=data)

```

might chance to:??
```
def get_ticker(self, symbol):
    if symbol:
        data = {
            'symbol': symbol
        }

        return self._get('market/orderbook/level1', False, data=data)
    else:
        return self._get('/api/v1/market/allTickers', False)

```

source: https://docs.kucoin.com/#get-ticker

**Comment by sammchardy** [comment]
Thanks for your help @nielskool can you check if this is now fixed in v2.1.0

**Comment by nielskool** [comment]
it is now always at market/allTickers but that is only the case when symbol=None.

so move tick_path = 'market/allTickers' into the if and else:
tick_path = 'market/orderbook/level1'

**Comment by LeKlex** [comment]
@

> it is now always at market/allTickers but that is only the case when symbol=None.
> 
> so move tick_path = 'market/allTickers' into the if and else:
> tick_path = 'market/orderbook/level1'

@nielskool 
I can confirm this.
For a quick fix, i changed the client library to:

```
data = {}
tick_path = 'market/allTickers'
if symbol is not None:
    tick_path = 'market/orderbook/level1'
    data = {
        'symbol': symbol
    }
    return self._get(tick_path, False, data=data)
```

**Comment by AndrewFarley** [comment]
This issue is still existing, the patch from LeKlex works, I'm going to submit a pull request so this functionality is no longer broken.  PR incoming...

**Comment by AndrewFarley** [comment]
It looks like someone else tried to fix it, but missed a line and made the opposite functionality broken (aka, made #54 happen again).  The PR above should fix it, blatantly copied from @LeKlex above, so no credit for me really.
